library(data.table)
power <- read.table("data/household_power_consumption.txt", h=T, sep=";", strings=F)
pow_Feb_1_2_2007 <- subset(power, Date == "1/2/2007" | Date == "2/2/2007")
sub_metering_1 <- as.numeric(pow_Feb_1_2_2007$Sub_metering_1)
sub_metering_2 <- as.numeric(pow_Feb_1_2_2007$Sub_metering_2)
sub_metering_3 <- as.numeric(pow_Feb_1_2_2007$Sub_metering_3)

timestamps <- strptime(paste(pow_Feb_1_2_2007$Date, pow_Feb_1_2_2007$Time), "%d/%m/%Y %H:%M:%S") 
png("plot3.png", h=480, w=480)
plot(timestamps, sub_metering_1, type="l", ylab="Energy Submetering", xlab="")
lines(timestamps, sub_metering_2, type='l', col='orangered2')
lines(timestamps, sub_metering_3, type='l', col='blue')
legend("topright", c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), lty=1, lwd=2.5, col=c("black", "orangered2", "blue"))
dev.off()
