library(data.table)
power <- read.table("data/household_power_consumption.txt", h=T, sep=";", strings=F)
pow_Feb_1_2_2007 <- subset(power, Date == "1/2/2007" | Date == "2/2/2007")
global_active_power <- as.numeric(pow_Feb_1_2_2007$Global_active_power)
global_reactive_power <- as.numeric(pow_Feb_1_2_2007$Global_reactive_power)
timestamps <- strptime(paste(pow_Feb_1_2_2007$Date, pow_Feb_1_2_2007$Time), "%d/%m/%Y %H:%M:%S") 
sub_metering_1 <- as.numeric(pow_Feb_1_2_2007$Sub_metering_1)
sub_metering_2 <- as.numeric(pow_Feb_1_2_2007$Sub_metering_2)
sub_metering_3 <- as.numeric(pow_Feb_1_2_2007$Sub_metering_3)
voltage <- as.numeric(pow_Feb_1_2_2007$Voltage)

png("plot4.png", h=480, w=480)
par(mfrow=c(2,2))
plot(timestamps, global_active_power, type="l", ylab="Global Active Power", xlab="")
plot(timestamps, voltage, type='l', xlab="datetime", ylab="Voltage")
plot(timestamps, sub_metering_1, type="l", ylab="Energy sub metering", xlab="")
lines(timestamps, sub_metering_2, type='l', col='orangered2')
lines(timestamps, sub_metering_3, type='l', col='blue')
legend("topright", c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), lwd=2, col=c("black", "orangered2", "blue"))
plot(timestamps, global_reactive_power, type='l', xlab='datetime', ylab='Global_reactive_power')
dev.off()
